name: Build and Relase papers
on:
  push:
    paths:
    - '**/relazione/*.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Compile e3 Latex document
      uses: dante-ev/latex-action@master
      with:
        root_file: esperienza_3_2021_11_07.tex
        working_directory: esperienza_3__misura_permeabilita_magnetica/relazione/
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/')
      name: Relase latests papers
      uses: softprops/action-gh-release@v1
      with:
        files: esperienza_3__misura_permeabilita_magnetica/relazione/esperienza_3_2021_11_07.pdf
